### ISSUE TITLE
Option to hide global symbols

### ISSUE THREAD

**Issue by BtbN** [yugr/Implib.so#11]
I'm converting a bunch of shared libs that depend on each other into delay loaded shims.
The second lib that links against the static loader of the first ends up exporting all of its symbols.

The fix for this seems to be to add a ".hidden $sym" to the respective https://github.com/yugr/Implib.so/blob/master/arch/x86_64/trampoline.S.tpl file.

Is there any reason to not add that by default? I can't immediately think of a reason why you'd ever want to build a shared library that just re-exports the symbols of the actual shared library.
In any case, an option to optionally hide those symbols would also be perfectly fine for me.

**Comment by yugr** [comment]
First of all, thank you for using the Implib.

> Is there any reason to not add that by default?

That is a good question. I wanted the shim to look like the original shared library to the rest of the executable. E.g. `dlsym` calls will return addresses of shim functions and when multiple libraries use the same shim, the first one will interpose the rest (saving I-cache and BTB).

But as you mention, this comes at the cost of bloating the interface of module which uses the shim. And it also slows down the shim call as it adds the PLT call to the equation.

It's not yet clear to me what should be the default, let me think it over.

I'll add a flag shortly.

**Comment by yugr** [comment]
Suggestions on what should be the default are welcome.

**Comment by yugr** [comment]
Shim symbols are now hidden by default (as having them public caused unsolvable issues with C++ constructors in libraries).
