### ISSUE TITLE
Android support?

### ISSUE THREAD

**Issue by BLuFeNiX** [yugr/Implib.so#12]
Hi, your README says:
```
support Android and OSX (none should be hard to add so let me know if you need it).
```

Just wanted to say Android support would be great if you are still open to adding it.

**Comment by yugr** [comment]
Hi, thank you for your interest in Implib.so.

I hope that code generated for Android should match the ARM/AArch64 Linux case. I'll try to make some tests over weekend to confirm this and report my findings here.

**Comment by BLuFeNiX** [comment]
Fantastic, thanks a bunch!

**Comment by yugr** [comment]
It seems that Android already works - I was able to generate shims via
```
implib-gen.py --target armv7-none-linux-androideabi ./libs/armeabi-v7a/libhello-neon.so
```
for armeabi-v7a ABI and
```
implib-gen.py --target aarch64-none-linux-androideabi ./libs/arm64-v8a/libhello-neon.so
```
for arm64-v8a and then successfully compiled them via `ndk-build`.

I have not _yet_ managed to test the generated code though as my Android experience is too outdated (in other words I failed to set up an emulator) but I believe it should just work.

**Comment by yugr** [comment]
@BLuFeNiX I wasn't able to set up an ARM image but simple Implib tests worked fine on Android 12.0 x86_64 image. Calling convention on Android ARM matches Linux so I do not expect any issues there.

I've updated the README to say that Android is supported and I will work on adding proper Android testing into CI.

Please let me know if you run into any issues.

**Comment by BLuFeNiX** [comment]
@yugr  Forgot to reply, just wanted to say thank you! I have tested it some, and will be using it again soon.
