### ISSUE TITLE
--no-dlopen option defines NO_DLOPEN in *.so.init.c not correctly

### ISSUE THREAD

**Issue by hirnrich** [yugr/Implib.so#13]
If the flag --no-dlopen is used your script defines NO_DLOPEN as follows in the *.so.init.c. I assume its a bug in your script.

```Python
#define NO_DLOPEN True
```
True is not defined and NO_DLOPEN is automatically assigned to 0 which is wrong in this case

I assume the error is at this line [https://github.com/yugr/Implib.so/blob/master/implib-gen.py#L544](https://github.com/yugr/Implib.so/blob/master/implib-gen.py#L544)

where

```Python
no_dlopen=not int(dlopen),
```
should probably be

```Python
no_dlopen=int(not dlopen),
```

P.s.: Thank you for this cool script! I will probably use it for a project

**Comment by yugr** [comment]
Fixed on trunk. Thank you for the fix and your interest in the project!
