### ISSUE TITLE
question regarding multi-threading limitation

### ISSUE THREAD

**Issue by ArnonHevlin** [yugr/Implib.so#20]
Thank you for providing this library!

I have a question in regard to multi-threading:
one of the project limitations is "proper support for multi-threading"

In my project initialization, I plan to read which libraries are necessary from configuration, and then load them with all their symbols using this project (by using _LIBNAME_tramp_resolve_all()).
Is there any danger in using multi-threading after all the libraries and their symbols are loaded?
Is there anything else I should look out for when multi-threading and using libraries that were loaded with this project?

Thanks.

**Comment by yugr** [comment]
First of all thank you for your interest in Implib.so, I hope it will be useful in your environment.

> Is there any danger in using multi-threading after all the libraries and their symbols are loaded?
Is there anything else I should look out for when multi-threading and using libraries that were loaded with this project?

No, after the library has been loaded (usually at program startup, unless you used `--lazy-load` or `--no-dlopen`) there should be no data races. Moreover, @Artem-B works on gh-19 which will synchronize the library load stage and generated code will be completely thread-safe.
