### ISSUE TITLE
[Feature Request] mipsel support

### ISSUE THREAD

**Issue by himekifee** [yugr/Implib.so#22]
Thanks a lot for your work on the project. I'm working on reverse engineering an embedded device with mipsel architecture. It would be brilliant if you have some time to make it work on mipsel arch so I can write some patches with it. Thanks.

**Comment by yugr** [comment]
Thank you for your interest in Implib.so.

I also wanted to add MIPS support, just postponed it due to lack of knowledge MIPS ABI/assembly. I'll try to cook something soon.

**Comment by himekifee** [comment]
`mipsel` specifically. I think it is `R_MIPS_REL32`.

**Comment by yugr** [comment]
I've added a branch with draft implementation but it currently fails some tests (in particular `tests/basic/run.sh mipsel` produces mismatched output for FP argument).

**Comment by himekifee** [comment]
Brilliant. Will have a test later after I get home. Thanks a lot.

**Comment by yugr** [comment]
@himekifee do you know if there is some online mipsel machine available for testing?

**Comment by himekifee** [comment]
I don't think so. I'm also using qrmu-mipsel-static to chroot.

**Comment by himekifee** [comment]
Does "dlsym" work for you? I have weird issues that might be relate to `uClibc` used by it not necessary the trampoline.

**Comment by yugr** [comment]
It does but I'm using Glibc.

**Comment by yugr** [comment]
> but it currently fails some tests (in particular `tests/basic/run.sh mipsel` produces mismatched output for FP argument).

It turned out that I wasn't aligning the stack properly. I fixed this bug and all the tests passed. The results have been merged to master.

**Comment by himekifee** [comment]
Do I need to specify some additional flags when working with `dlsym`? Tried to link against target `libdl` but no help.

**Comment by yugr** [comment]
Linking to libdl should be enough. I've added a call to `dlerror()` on trunk to print more detailed message in case of `dlsym` error.

**Comment by himekifee** [comment]
That print didn't seem to be triggered for me

**Comment by himekifee** [comment]
I may get I bit confused here. The situation is the program used libdl to load the target lib, which is the one I'm currently modifying. The lib(trampoline) then uses dlopen again to load the original lib. Will this cause issues?

**Comment by himekifee** [comment]
And a weird one is, I can set a breakpoint in gdb as it founds the modified lib address, but not the original lib. I assume it failed to load the original lib. Any way to debug? I can give you a shell if you like to. Thank you very much.

**Comment by yugr** [comment]
Yes, shell would be ok (with details on how to compile and run the program).

**Comment by himekifee** [comment]
Do you have a telegram or discord?

**Comment by yugr** [comment]
My TG is the_real_yugr

**Comment by himekifee** [comment]
Issue solved. Thanks again.
