### ISSUE TITLE
Invalid asm for arm when there are more than 256/4096 functions

### ISSUE THREAD

**Issue by impynutz** [yugr/Implib.so#25]
Used version: 11f7b4c117b553794fb796077bb298e2fd3cf464

After generating with` ./implib-gen.py --target arm-linux-gnueabihf lib.so` I get
`implib-gen.py: warning: library 'lib.so' contains data symbols which won't be intercepted: [...symbols]`
Not sure this is relevant here, but just so it's mentioned.

Then in the generated code after $number gets bigger than 256:
```
lib.so.tramp.S: Assembler messages:
lib.so.tramp.S:11944: Error: invalid literal constant: pool needs to be closer
```
from the generated tramp +11944
```file
  ldr ip, =257
```
I found some comments on this error, but nothing helped.
- using LTORG directive in asm (not sure I used this correctly)
- using compiler flag -ffunction-sections
- using compiler flag -mlong-calls
- also had the flag -mthumb-interwork set

And also here after $offset gets bigger than 4095:
```
lib.so.tramp.S:47218: Error: bad immediate value for offset (4096)
```
from the generated tramp +47218
```
  ldr ip, [ip, #4096]
```
Can this just be fixed by loading the constant into a register first?
```
  ldr r1, #$offset
  ldr ip, [ip, r1]
```

**Comment by yugr** [comment]
Thank you for the report, indeed we'll need a register move in this case... I'll try to prepare fix this week.

**Comment by yugr** [comment]
This seems to be fixed on trunk for ARM now. MIPS is still tbd so I'm not closing this bug.

**Comment by yugr** [comment]
MIPS fixed as well.

**Comment by yugr** [comment]
@impynutz closing for now, please reopen if problem persists.

Thank you for trying Implib.so and reporting this bug.
