### ISSUE TITLE
Aarch64 trampoline asm can't handle large $number

### ISSUE THREAD

**Issue by Artem-B** [yugr/Implib.so#26]
https://github.com/yugr/Implib.so/blob/69a90e33e97cb3058121ce3345821a91205ff7d0/arch/aarch64/trampoline.S.tpl#LL32C18-L32C18

`mov` can only handle the values that fit into 16 bit. To guarantee that we can load larger values we should be using `mov + movk`. https://godbolt.org/z/9f5zx3e9r

**Comment by yugr** [comment]
@Artem-B I think I fixed it on master, please check.

**Comment by yugr** [comment]
Closing for now, let me know if problem persists.

**Comment by Artem-B** [comment]
Thank you for the quick fix. It appears to be working.
