### ISSUE TITLE
Library soname should be used as load name

### ISSUE THREAD

**Issue by ilya-fedin** [yugr/Implib.so#27]
Build system knows only the build-time handle which has no soversion but those files are usually not installed on production systems (that is, not having -dev packages installed). Implib should deduce the soname (probably using `readelf -d`?) and use it rather than the basename.

**Comment by yugr** [comment]
So to give an example, if I apply `implib-gen` to say `/usr/lib/x86_64-linux-gnu/libkrb5.so.3.3` it will currently try to load that same library:
```
lib_handle = dlopen("libkrb5.so.3.3", RTLD_LAZY | RTLD_GLOBAL);
```
You suggest to change that to use SONAME instead:
```
lib_handle = dlopen("libkrb5.so.3", RTLD_LAZY | RTLD_GLOBAL);
```
Sounds like a reasonable change.

**Comment by ilya-fedin** [comment]
My use-case is to call implib-gen from cmake. I have a cmake function that accepts library name like `wayland-client` and then gets a full path with cmake's `find_library`. It ends with something like `/usr/lib64/libwayland-client.so`. This makes the code generated by implib to not to work on production systems as it loads `libwayland-client.so` which is not present as it's a part of -dev package. I don't see a way to get the right library name from cmake other than parsing readelf output with cmake which really feels too much.

Of course, implib-gen shouldn't use the parsed soname as the prefix for generated files as ninja (used by cmake) excepts the command to generate output files and I should know their name in advance to specify them (as well as to be able to add them to a target).

**Comment by yugr** [comment]
Thanks, I understand the problem now.

> Of course, implib-gen shouldn't use the parsed soname as the prefix for generated files as ninja (used by cmake) excepts the command to generate output files and I should know their name in advance to specify them (as well as to be able to add them to a target)

Agreed. I think the same should apply to prefixes of helper functions (`_XXX_tramp_resolve_all`, etc.).

**Comment by yugr** [comment]
Should be fixed on master now.
