### ISSUE TITLE
missing .note.GNU-stack section implies executable stack

### ISSUE THREAD

**Issue by njzjz** [yugr/Implib.so#34]
When I use CMake to compile and link the generated `.tramp.S` file, the following warnings appear:

```
[  6%] Linking CXX shared library libdeepmd_dyn_cudart.so
ld: warning: CMakeFiles/deepmd_dyn_cudart.dir/libcudart.so.tramp.S.o: missing .note.GNU-stack section implies executable stack
ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
```

My version:
GNU ld version 2.39-9.fc38
gcc (conda-forge gcc 12.3.0-2) 12.3.0
cmake version 3.27.6

**Comment by yugr** [comment]
Thank you for reporting this issue. I've added the `.note.GNU-stack` section to assembly, please check if this is fixed now.

**Comment by njzjz** [comment]
Thanks, it works for me.
