### ISSUE TITLE
question: Is it possible to use in APK?

### ISSUE THREAD

**Issue by ghost** [yugr/Implib.so#36]
To test it, I took some applications that use lib/arm64-v8a/libexample.so in their work. 
Generated with ```implib-gen.py --target aarch64-none-linux-android libexample.so```

In ``libexample.so.init.c``, replaced the line with ```dlopen(“libexample_stub.so”)``` 
Compiled with `-shared` and `-DIMPLIB_EXPORT_SHIMS`. I put ```libexample.so``` and ```libexample_stub.so``` in lib/arm64-v8a, but it always crashes.

**Comment by yugr** [comment]
Sorry for late reply, I only got to this on weekend.

Simple command-line apps should work fine on Android:
* I installed SDK and emulator according to instructions [here](https://github.com/namhyung/uftrace/pull/1605#issuecomment-1406785744)
* I used the following simple program and library:
```
$ cat prog.c
#include <stdio.h>

extern int foo(int x, int y);

int main() {
  printf("%d\n", foo(10, 11));
  return 0;
}
$ cat lib.c
int foo(int x, int y) { return x * y; }
```
* Finally I compiled and ran via
```
x86_64-linux-android35-clang lib.c -shared -fPIC -o liblib.so

./Implib.so/implib-gen.py liblib.so

x86_64-linux-android35-clang prog.c liblib.so.tramp.S liblib.so.init.c -DIMPLIB_EXPORT_SHIMS

adb push liblib.so a.out /data
adb shell 'chmod +x /data/a.out /data/liblib.so'
adb shell 'cd /data; LD_LIBRARY_PATH=. ./a.out'
```
and got `110` as expected.

Perhaps you could provide a full reprocase? Please note that I'm not super experienced with Android so the more details you provide the better...
