### ISSUE TITLE
usage of Implib.so

### ISSUE THREAD

**Issue by lili2012** [yugr/Implib.so#4]
My teacher said that even though we statically link a shared library the symbol of shared library's functions are still delay loaded when say an executable need it. So what is the advantage of Implib.so?

**Comment by yugr** [comment]
> the symbol of shared library's functions are still delay loaded when say an executable need it

Yes but
* relocations for data symbols are still processed eagerly
* library constructors are always executed and if they call any functions inside the library, those need to be resolved, loaded to RAM, etc. (and if they call functions from other libs, those need to be resolved as well)

Also all library dependencies have to loaded (transitively) and their constructors executed.

> So what is the advantage of Implib.so?

In addition to speeding up startup and saving resources (for the reasons described above), it also allows flexible control over which library needs to be loaded (e.g. you may decide to load library version which is optimized for particular CPU).
