### ISSUE TITLE
Segmentation fault.

### ISSUE THREAD

**Issue by Alan-Turing-Ko** [yugr/Implib.so#5]
Thanks for great library.
I'm trying to use your library on armv7 architecture.
I've compiled program and library on arm-linux-gnueabihf-g++ compiler.
Generating stub files and resolving my own so in runtime are OK.
But when I use functions, I got segmentation fault.
I am newbie on arm assembly, so I can't debug well, but referencing ip register arise segmentation fault.

ldr ip, 3f
2:
  add ip, pc, ip
  ldr ip, [ip, #336]

  cmp ip, #0

  // Fast path
  bxne ip

  // Slow path
  ldr ip, =84
  push {ip}

Hope to any suggestions.
Best regards.

**Comment by yugr** [comment]
Hi, I am sorry to hear that you have issues. Could you provide a repro case so that I can investigate?

**Comment by yugr** [comment]
FYI here's how I test ARM code:
```
$ arm-linux-gnueabi-gcc -g -O2 -shared -fPIC interposed.c -o libinterposed.so
$ implib-gen.py -q --target arm libinterposed.so
$ arm-linux-gnueabi-gcc -g -O2 main.c test.c libinterposed.so.tramp.S libinterposed.so.init.c -ldl
$ LD_LIBRARY_PATH=.: qemu-arm -L /usr/arm-linux-gnueabi -E LD_LIBRARY_PATH=. ./a.out
```

**Comment by yugr** [comment]
Closing, please reopen if repro is available.
