### ISSUE TITLE
Possible to throw an exception on failure to load target library?

### ISSUE THREAD

**Issue by pkulchenko** [yugr/Implib.so#7]
@yugr, thank you for providing this tool! It looks to do most of what I need, but I'm wondering if it can be extended to throw an exception if the target library can't be loaded (similar to https://github.com/jackyf/so-stub).

My use case. I need to link statically against a library that can be missing on the target computer, but don't want to abort loading the entire module/executable, as that functionality may be optional. I've tried other options (some of which you listed in README), but none of them work well for this use case. I'd like to build an .so file using your tool that would replace the (potentially missing) library, so that if the target library is present, then the calls get forwarded to it (like you do now), but if it's missing, the (run-time) exception is thrown, but the library itself is loaded to satisfy the dependency.

Also, you mentioned that you can do 32-bit variant as well, which would be great for my case (as I need both 64bit and 32bit versions). How difficult would be to add it?

**Comment by yugr** [comment]
I agree that user might need to customize behavior on error. I suggest to add a flag to provide custom callback on module/symbol load failure (which would throw exception in your case). Would that be ok?

As for i386 - it's not super-hard, I just avoided implementing it due to clumsy PIC support there (and also because I thought noone would be interested in this target it nowadays). I'll work on i386 later this week and update on how it goes.

Thanks for trying out the tool.

**Comment by pkulchenko** [comment]
> I suggest to add a flag to provide custom callback on module/symbol load failure (which would throw exception in your case). Would that be ok?

This probably won't work for my scenario, as the fallback logic should ideally be in the module itself. I'll have to do `load("X"); if failed load("X-stub")` and it looks like I should be able to use `dlopen-callback` to set that up; I'll give it a try.

> As for i386 - it's not super-hard, I just avoided implementing it due to clumsy PIC support there (and also because I thought this target is no longer used much). I'll work on i386 later this week and update on how it goes.

Would be great; thank you!

**Comment by yugr** [comment]
Yes, hopefully dlopen callback will work for you (let me know if it does not).

**Comment by yugr** [comment]
I've pushed i386 support, let me know if it works for you (`tests/1/run.sh i386` works in my VM). Also, did dlopen callback work?

**Comment by pkulchenko** [comment]
@yugr, thank you for the updates. I got the tests working for both 64bit and 32bit platforms, but I can't get it working for my use case. I'll post the details, but so far it looks like it hangs on the first call, but I don't see anything interesting in `strace` that would explain why it's doing that. The effect is the same on both platforms, so, doesn't seem to be a fluke. I'll post the exact command and the configuration I'm using, but need to finish reviewing the details.

**Comment by yugr** [comment]
Interesting, please post a repro. Or you could also try checking what happens inside gdb (just break in the first wrapper).

**Comment by yugr** [comment]
Can your issue be related to #8?

**Comment by pkulchenko** [comment]
Doesn't seem like it, but I'm still figuring it out. I'll update when I get more details.

Would calling `throw std::runtime_error()` from a callback interfere with stack unwinding?

**Comment by yugr** [comment]
> Would calling throw std::runtime_error() from a callback interfere with stack unwinding?

Should work ok (I've added test in 80361dc4 just in case, passes locally).

**Comment by yugr** [comment]
FYI I realize it might be complicated to provide a repro but perhaps gdb stacktrace provides some hints about the reasons for the bug?

**Comment by yugr** [comment]
Closing, please reopen if new info is available.
