### ISSUE TITLE
Generating vtables and typeinfos

### ISSUE THREAD

**Issue by ttholy** [yugr/Implib.so#9]
Would it be possible to generate the counterparts for "exported" vtables and typeinfos? These symbols are needed on caller's side if one needs to do e.g. a dynamic_cast or if virtual dtor of "imported" class is inlined. 

On Windows the compiler generates vtable containing addresses of stub (trampoline) functions on caller's side. The typeinfos are duplicated in the caller's module (exe/dll) as well so delay loading works fine even with polymorhic classes and RTTI involved.

Would it be possible to do the same on Linux?

Thanks, Tomas

**Comment by yugr** [comment]
That's an interesting one. Leaving complexities of parsing Itanium ABI aside, adding wrappers for vtables would require adding stubs for _all_ virtual methods referenced in them. This is possible iff each virtual method is exported which is not always true: methods might be hidden via `__attribute((visibility("hidden")))` or simply `-fvisibility-inlines-hidden`. So I'm afraid in general the answer is "no".

**Comment by yugr** [comment]
In theory if virtual method is hidden we could still lazily read it's address from library's vtable at runtime using offset from vtable start. But I'm still not sure how to identify if a given unnamed vtable entry is atually a method (vs typeinfo or virtual offset).

**Comment by ttholy** [comment]
Generating these symbols could be optional. If re

**Comment by yugr** [comment]
Ok, I should be able to support a limited use-case. It's kind of non-trivial thing to add/debug so might take time to add though.

**Comment by ttholy** [comment]
That would be great. Thanks a lot!

**Comment by yugr** [comment]
Please check ToT, I've added vtable support and it seems to work in simple cases.

**Comment by ttholy** [comment]
Thanks, I'll give it a try
